spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springboot_shiro?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver


    freemarker:
        suffix: .html
        charset: utf-8
        # 关闭缓存，模板热部署
        # cache: false
    mvc:
        # 配置静态资源映射路径，/public、/resources路径失效
        static-path-pattern: /static/**
mybatis:
    mapper-locations: classpath:mappers/*.xml
